### ISSUE TITLE
How do I remove this weird bar at the end?

### ISSUE THREAD

**Issue by krikmo** [jomurgel/PocketCaster#1]
![ss](https://cloud.githubusercontent.com/assets/12498661/8513709/1fcc3db2-234c-11e5-9c06-949083752c0d.jpg)

**Comment by jomurgel** [comment]
Eduardo,

Sorry for the visual obstruction.  I’m looking into this issue.  It may be a Windows setting, but I want to confirm before giving you a definite answer and/or updating the app.

Thanks!

**Comment by krikmo** [comment]
Thanks for all the hard work! :)

**Comment by jomurgel** [comment]
Eduardo,

I've updated the app here and in the chrome store.  The bar should be absent now.

Thanks!

**Comment by krikmo** [comment]
Thanks for the update, but now it's crashing everytime I open it. 
![pocket-caster](https://cloud.githubusercontent.com/assets/12498661/8739549/6db18f26-2c13-11e5-8d68-bd8d6573bdbd.png)
I liked your project so much that I created a [simplified version](https://github.com/oduduserra/PocketCasts) just for fun.
It's not an awesome app like yours, but will do the job for now.

EDIT: I looked at the changes in your code, there's nothing there causing the crashes. Maybe the issue is here at my end. Will try on Windows later (using Linux now).

**Comment by jomurgel** [comment]
Eduardo,

I've released version 1.1.2 that should fix your issue (removed some unnecessary code) while resolving your scroll bar issue from earlier.  I've tested Windows, Chromebook, Mac and Linux with positive results.  

Good job on your app as well! Glad I could inspire!
