### ISSUE TITLE
Move to Standalone Desktop App

### ISSUE THREAD

**Issue by jomurgel** [jomurgel/PocketCaster#5]
Since Google is discontinuing support, noted in #3, I'm looking into standalone desktop app options with cross-browser support.  Perhaps using [electron](https://electron.atom.io/) since Shifty Jelly doesn't appear to have any interest in creating a desktop app.

Alternative discussion or options are welcome.

**Comment by spettinichi** [comment]
I'm willing to help out with an electron app. What kind of timeframe did you have in mind?

**Comment by spettinichi** [comment]
I reached out to ShiftyJelly on Twitter just to verify there were no impending plans for a Windows app. They do have a native Mac app, but that's all so far. An electron app would still be useful.
https://twitter.com/pocketcasts/status/916099712536768513

**Comment by jomurgel** [comment]
Well, that's a heck of a thing I didn't know existed, though I imagine that's not very widely advertised.  Googling returned no results for that app or the block for that matter.

That said, I think even if it's as simple as the current Google Standalone App, it'd be appreciated cross-platform.

**Comment by jomurgel** [comment]
I have to refamiliarize myself with Electron, but I'd like to try and roll something out before Christmas I think.

Created a new [repo](https://github.com/jomurgel/PocketCasterApp) and invited you as a collaborator @xeratun.  Will be diving into the [docs](https://electron.atom.io/docs/) this tomorrow and this weekend to get a better idea of the work involved.

**Comment by spettinichi** [comment]
I think the Mac app is new along with the beta, so they may not be featuring it very prominently yet while it's in the beta period.
Sounds good. I got the invite.
